config/routes.rb
Rails.application.routes.draw do
  root "todos#index"
  get "/todos", to: "todos#index"
  get "/todos/new", to: "todos#new"
  post "/todos", to: "todos#create"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
    respond_to :js
  end

  def create
    user = User.first
    @todo = Todo.new(todo_params)
    @todo.user_id = user.id

    @todo.save
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoAppRails
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/todos/_todo_modal.html.haml
#todomodal.modal.fade{'aria-hidden' => 'true', role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title New ToDo
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', type: 'button'}
          %span{'aria-hidden' => 'true'} ×
      .modal-body
        = form_with model: @todo do |form|
          %div
            = form.label :title
            %br/
            = form.text_field :title
          %div
            = form.label :text
            %br/
            = form.text_area :text
          %div
            = form.submit

app/views/todos/index.html.haml
.container
  %h2 ToDos
  %table.table
    %thead
      %tr
        %th Title
        %th Text
    %tbody
      - @todos.each do |todo|
        %tr
          %td= todo.title
          %td= todo.text

.modal-container

= link_to('New ToDo', todos_new_path, remote: true)

app/views/todos/new.js.haml
$('.modal-container').append("#{escape_javascript( render partial: 'todo_modal')}");
$('#todomodal').modal('show')